### ISSUE TITLE
Spell check code with cSpell

### ISSUE THREAD

**Issue by gshaw** [gshaw/notes#19]
I've been using cSpell because of the better VS Code integration and better developer ergonomics. A previous version of this note recommend code spell. 

Unfortunately it's a Node tool so you need to have Node installed to get it.

```sh
brew install node
npm install -g cspell@latest
```

To run a spell check use `cspell lint --no-progress .`

Create a `cspell.config.yml` in the project root with the following contents to add words you want to ignore or add comments in the source code to ignore words for the specific file.

```elixir
# cspell:ignore ref_autoid
```

```yml
---
$schema: "https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json"
version: "0.2"
language: en
allowCompoundWords: true
ignorePaths:
  - "_build/*"
  - ".git/*"
  - "assets/vendor/*"
  - "cspell.config.yml"
  - "deps/*"
  - "erl_crash.dump"
  - "priv/static/assets/*"
words:
  - aria-describedby
  - aria-labelledby
```

Source:
* https://cspell.org

**Comment by gshaw** [comment]
**Update**: I've been using cSpell instead because of the better VS Code integration and better developer ergonomics.

Unfortunately it's a Node tool so you need to have Node installed to get it.

```sh
brew install node
npm install -g cspell@latest
```

To run a spell check use `cspell lint --no-progress .`

Create a `cspell.config.yml` in the project root with the following contents to add words you want to ignore or add comments in the source code to ignore words for the specific file.

```elixir
# cspell:ignore ref_autoid
```

```yml
---
$schema: "https://raw.githubusercontent.com/streetsidesoftware/cspell/main/cspell.schema.json"
version: "0.2"
language: en
allowCompoundWords: true
ignorePaths:
  - "_build/*"
  - ".git/*"
  - "assets/vendor/*"
  - "cspell.config.yml"
  - "deps/*"
  - "erl_crash.dump"
  - "priv/static/assets/*"
words:
  - aria-describedby
  - aria-labelledby
```
